version: '3.5'

services:
  php:
#    image: php:7.4-cli
    build: .docker/php
    container_name: PHP
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    volumes:
      - .:/var/www/html
    tty: true